version: 0.2

env:
  parameter-store:
    DOCKER_HUB_USERNAME: "/codebuild/dockerhub/username"
    DOCKER_HUB_PASSWORD: "/codebuild/dockerhub/password"

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub"
      - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t $DOCKER_HUB_USERNAME/flask-codebuild-app:latest .

  post_build:
    commands:
      - echo "Pushing image"
      - docker push $DOCKER_HUB_USERNAME/flask-codebuild-app:latest

artifacts:
  files:
    - appspec.yml
    - scripts/**
