version: 0.2

env:
  parameter-store:
    DOCKER_HUB_USERNAME: "/codebuild/dockerhub/username"
    DOCKER_HUB_PASSWORD: "/codebuild/dockerhub/password"
  variables:
    IMAGE_NAME: "flask-codebuild-app"

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub"
      - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME ganesh1452/flask-codebuild-app:GANESH IMAGE

  post_build:
    commands:
      - echo "Pushing Docker image"
      - docker push ganesh1452/flask-codebuild-app:GANESH IMAGE
